### ISSUE TITLE
DOM Events

### ISSUE THREAD

**Issue by grantcarthew** [axwalker/aurelia-observer-patterns#1]
Hi @axwalker,

I needed this example of observer patterns, thanks mate. I have been having trouble with getting a parent VM to cache form data from a child custom elements events. Ref: https://github.com/aurelia/framework/issues/371

I was using the DOM to raise events with this function:

``` js
  raiseChangeEvent (element) {
    logger.debug('raiseChangeEvent')
    let changeEvent
    if (window.CustomEvent) {
      changeEvent = new CustomEvent('change', {
        bubbles: true
      })
    } else {
      changeEvent = document.createEvent('CustomEvent')
      changeEvent.initCustomEvent('change', true, true)
    }
    element.dispatchEvent(changeEvent)
  }
```

Got the idea from @vheissu here:[Aurelia Custom Elements Custom Callbac Events Tutorial](http://ilikekillnerds.com/2015/08/aurelia-custom-elements-custom-callback-events-tutorial/)

This worked on simple custom elements, however on a couple of complex ones I have it was raising the event before the binding was being updated.

It's late, I will try these out tomorrow if I can.

Is using the DOM a valid method also?

**Comment by axwalker** [comment]
Hey, sorry for the delayed response - I'm away from a computer for a couple of days.

Did you have any luck with the other methods? I hadn't considered these DOM events much, but I can have a proper look at this tomorrow.

From a quick glance at your case, my first thought would be to maybe use something like method 1 (two-way bindables) along with property observers in the parent - I can explain properly tomorrow. Do you have a full example I can clone/run with the issue you're having?
