### ISSUE TITLE
Document another pattern: passing callback from parent to child

### ISSUE THREAD

**Issue by atsu85** [axwalker/aurelia-observer-patterns#2]
Thanks for explaining different observer patterns. However You have left out one of my favorite pattern: passing callback(setter function) from parent to child component, that can use it to pass data back to parent component.

I sent a pull request #3 with the implementation for this pattern

**Comment by atsu85** [comment]
Unfortunately I can't send a PR for documentation. @axwalker, please update the wiki page to include smth like that:

### Setter callback

Another option is passing the setter/callback function reference from parent to child component using `.call` binding. Then the reference to the callback function that is defined in parent will be stored on child component and it can be used as normal function with the parameters specified by the function declaration in parent component.

Full code: [here](https://github.com/atsu85/aurelia-observer-patterns/tree/setter-callback)

The key pieces:

Add the setter/callback function that You want to be called by the child component:

``` typescript
selectPerson(person) {
    alert(`${person.firstName} ${person.lastName} selected`);
}
```

Pass the callback function to the child component:

``` html
<person-list people.bind="people" select-person-callback.call="selectPerson($event)"></person-list>
```

Add bindable field for the function reference to child component with a corresponding method to call it when the relevant button is pressed:

``` typescript
@bindable() selectPersonCallback: (Person) => void;

selectPerson(person) {
    this.selectPersonCallback(person);
}
```

Just like with the previous example using bindables,
add an event trigger for when a button is pressed in person-list.html:

``` html
<button class="btn" click.trigger="selectPerson(person)">Select</button>
```

**Comment by axwalker** [comment]
Thanks a lot for the contribution! Will add this to the wiki page now.

**Comment by axwalker** [comment]
I've added that to the wiki. Thanks again!

**Comment by atsu85** [comment]
Thank You too. 
Is this issue left open intentionally?
