### ISSUE TITLE
Document another pattern: injecting shared state object

### ISSUE THREAD

**Issue by atsu85** [axwalker/aurelia-observer-patterns#4]
There is one more simple pattern, that I've used often: 
Injecting shared state object to both parent and child component.

I sent a pull request #5 with the implementation for this pattern.

**Comment by atsu85** [comment]
_Unfortunately I can't send a PR for documentation. @axwalker, please update the wiki page to include smth like that (I'd add it after "Setter callback" pattern):_

### Injecting shared state object

Another option is using Dependency Injection to inject shared state object to both (parent and child) components. Then the shared state object can be used as normal object to set property value in child component and to read (or even observe value changes) it in parent.

Full code: [here](https://github.com/atsu85/aurelia-observer-patterns/tree/shared-state-object)

The key pieces:

Create a class for the shared state (so an instance of it can be created by Aurelia Dependency Injection Container)

``` typescript
import {Person} from './person';

export class SelectedPersonHolder {
  person: Person;
}
```

Now inject the (singleton) instance to both parent ...

``` typescript
import {SelectedPersonHolder} from './SelectedPersonHolder';
import {autoinject} from 'aurelia-framework';

@autoinject
export class App {
    ...
    constructor(private selectedPersonHolder: SelectedPersonHolder) {
    }
}
```

...and child component, where it is used to change the shared state:

``` typescript
import {bindable, autoinject} from 'aurelia-framework';
import {SelectedPersonHolder} from './SelectedPersonHolder';

@autoinject
export class PersonList {
    ...
    constructor(private selectedPersonHolder: SelectedPersonHolder) {
    }

    selectPerson(person) {
        this.selectedPersonHolder.person = person;
    }
}
```

> **Note:** The instance must be created by Aurelia (not manually, for example `new SelectedPersonHolder()`), otherwise changes won't be detected by Aurelia!

Add the click event handler to the child component template to assigns new value to the shared state:

``` html
<button class="btn" click.delegate="selectPerson(person)">Select</button>
```

If in the parent component You only need to display the value set by child component there isn't much more to do, other than adding it to the html template:

``` html
selected: ${selectedPersonHolder.person.firstName} ${selectedPersonHolder.person.lastName}
```

But if You also want to execute custom code when the value is changed, You can subscribe to property change to receive the new (and old) value.

``` typescript
import {Person} from './person';
import {SelectedPersonHolder} from './SelectedPersonHolder';
import {autoinject, BindingEngine, Disposable} from 'aurelia-framework';

@autoinject
export class App {
    ...
    observerDisposer: Disposable;

    constructor(private selectedPersonHolder: SelectedPersonHolder, private bindingEngine: BindingEngine) {
      this.observerDisposer = this.bindingEngine.propertyObserver(this.selectedPersonHolder, "person")
      .subscribe((person: Person, oldValue: Person) => {
        alert(`${person.firstName} ${person.lastName} selected`);
      });
    }

    deactivate() {
      // make sure to call it when component doesn't need the changes any more
      this.observerDisposer.dispose();
    }
}
```

**Comment by axwalker** [comment]
Merged and added to wiki. Thanks!

**Comment by atsu85** [comment]
Thanks, I found that the link to the full code still points to my own repo - You may want to change it like You did for my previous pull request ;)

**Comment by axwalker** [comment]
Ah yes, good catch. Fixed!
